spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/authenticationapi
    username: root
    password: 12345678

api:
  security:
    token:
      secret: imagineaquialgomuitoseguro